apiVersion: v1
kind: Service
metadata:
  name: siem-front
spec:
  selector:
    app: siem-front
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 9000
