apiVersion: v1
kind: Service
metadata:
  name: siem-validador
spec:
  selector:
    app: siem-validador
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 7777

